export const banksList = [
  {
    id: 879,
    name: "78 Finance Company Ltd",
    slug: "78-finance-company-ltd-ng",
    code: "40195",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 707,
    name: "9jaPay Microfinance Bank",
    slug: "9japay-microfinance-bank-ng",
    code: "090629",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 302,
    name: "9mobile 9Payment Service Bank",
    slug: "9mobile-9payment-service-bank-ng",
    code: "120001",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 174,
    name: "Abbey Mortgage Bank",
    slug: "abbey-mortgage-bank-ng",
    code: "404",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 188,
    name: "Above Only MFB",
    slug: "above-only-mfb",
    code: "51204",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 627,
    name: "Abulesoro MFB",
    slug: "abulesoro-mfb-ng",
    code: "51312",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 1,
    name: "Access Bank",
    slug: "access-bank",
    code: "044",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 3,
    name: "Access Bank (Diamond)",
    slug: "access-bank-diamond",
    code: "063",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 495,
    name: "Accion Microfinance Bank",
    slug: "accion-microfinance-bank-ng",
    code: "602",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 897,
    name: "Adamawa Mortgage Bank Limited",
    slug: "adamawa-mortgage-bank-limited-ng",
    code: "90102",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 687,
    name: "Aella MFB",
    slug: "aella-mfb-ng",
    code: "50315",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 780,
    name: "AG Mortgage Bank",
    slug: "ag-mortgage-bank-ng",
    code: "90077",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 676,
    name: "Ahmadu Bello University Microfinance Bank",
    slug: "ahmadu-bello-university-microfinance-bank-ng",
    code: "50036",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 300,
    name: "Airtel Smartcash PSB",
    slug: "airtel-smartcash-psb-ng",
    code: "120004",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 698,
    name: "AKU Microfinance Bank",
    slug: "aku-mfb",
    code: "51336",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 497,
    name: "Akuchukwu Microfinance Bank Limited",
    slug: "akuchukwu-microfinance-bank-limited-ng",
    code: "090561",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 872,
    name: "Al-Barakah Microfinance Bank",
    slug: "al-barakah-microfinance-bank-ng",
    code: "50055",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 27,
    name: "ALAT by WEMA",
    slug: "alat-by-wema",
    code: "035A",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 906,
    name: "Alert MFB ",
    slug: "alert-mfb-ng",
    code: "51074",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 857,
    name: "Alpha Morgan Bank",
    slug: "alpha-morgan",
    code: "108",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 790,
    name: "Alternative bank",
    slug: "the-alternative-bank-ng",
    code: "000304",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 179,
    name: "Amju Unique MFB",
    slug: "amju-unique-mfb",
    code: "50926",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 614,
    name: "Aramoko MFB",
    slug: "aramoko-mfb",
    code: "50083",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 63,
    name: "ASO Savings and Loans",
    slug: "asosavings",
    code: "401",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 793,
    name: "Assets Microfinance Bank",
    slug: "assets-microfinance-bank-ng",
    code: "50092",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 297,
    name: "Astrapolaris MFB LTD",
    slug: "astrapolaris-mfb",
    code: "MFB50094",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 759,
    name: "AVUENEGBE MICROFINANCE BANK",
    slug: "avuenegbe-microfinance-bank-ng",
    code: "090478",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 778,
    name: "AWACASH MICROFINANCE BANK",
    slug: "awacash-microfinance-bank-ng",
    code: "51351",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 796,
    name: "AZTEC MICROFINANCE BANK LIMITED",
    slug: "aztec-microfinance-bank-limited-ng",
    code: "51337",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 181,
    name: "Bainescredit MFB",
    slug: "bainescredit-mfb",
    code: "51229",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 686,
    name: "Banc Corp Microfinance Bank",
    slug: "banc-corp-microfinance-bank-ng",
    code: "50117",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 880,
    name: "Bank78 Microfinance Bank",
    slug: "bank78-microfinance-bank-ng",
    code: "11072",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 908,
    name: "BANKIT MFB",
    slug: "bankit-mfb-ng",
    code: "50572",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 832,
    name: "BANKIT MICROFINANCE BANK LTD",
    slug: "bankit-microfinance-bank-ltd-ng",
    code: "50572",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 689,
    name: "BANKLY MFB",
    slug: "ampersand-microfinance-bank-ng",
    code: "51341",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 777,
    name: "Baobab Microfinance Bank",
    slug: "baobab-microfinance-bank-ng",
    code: "MFB50992",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 783,
    name: "BellBank Microfinance Bank",
    slug: "bellbank-microfinance-bank-ng",
    code: "51100",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 589,
    name: "Benysta Microfinance Bank Limited",
    slug: "benysta-microfinance-bank-limited",
    code: "51267",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 886,
    name: "Berachah Microfinance Bank Ltd.",
    slug: "berachah-microfinance-bank-ltd-ng",
    code: "50122",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 771,
    name: "Beststar Microfinance Bank",
    slug: "beststar-microfinance-bank-ng",
    code: "50123",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 816,
    name: "BOLD MFB",
    slug: "bold-mfb-ng",
    code: "50725",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 901,
    name: "Boost Microfinance Bank",
    slug: "boost-microfinance-bank-ng",
    code: "51449",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 815,
    name: "Bosak Microfinance Bank",
    slug: "bosak-microfinance-bank-ng",
    code: "650",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 108,
    name: "Bowen Microfinance Bank",
    slug: "bowen-microfinance-bank",
    code: "50931",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 697,
    name: "Branch International Finance Company Limited",
    slug: "branch",
    code: "FC40163",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 867,
    name: "Brent Mortgage bank",
    slug: "brent-mortgage-bank-ng",
    code: "90070",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 817,
    name: "BuyPower MFB",
    slug: "buypower-mfb-ng",
    code: "50645",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 82,
    name: "Carbon",
    slug: "carbon",
    code: "565",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 781,
    name: "Cashbridge Microfinance Bank Limited",
    slug: "cashbridge-mfb-ng",
    code: "51353",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 692,
    name: "CASHCONNECT MFB",
    slug: "cashconnect-mfb-ng",
    code: "865",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 915,
    name: "Cedrus MFB",
    slug: "cedrus-mfb-ng",
    code: "51437",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 74,
    name: "CEMCS Microfinance Bank",
    slug: "cemcs-microfinance-bank",
    code: "50823",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 904,
    name: "Centrum Finance",
    slug: "centrum-finance-ng",
    code: "050032",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 284,
    name: "Chanelle Microfinance Bank Limited",
    slug: "chanelle-microfinance-bank-limited-ng",
    code: "50171",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 704,
    name: "Chikum Microfinance bank",
    slug: "chikum-microfinance-bank-ng",
    code: "312",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 2,
    name: "Citibank Nigeria",
    slug: "citibank-nigeria",
    code: "023",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 755,
    name: "CITYCODE MORTAGE BANK",
    slug: "citycode-mortage-bank-ng",
    code: "070027",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 691,
    name: "Consumer Microfinance Bank",
    slug: "consumer-microfinance-bank-ng",
    code: "50910",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 874,
    name: "Cool Microfinance Bank Limited",
    slug: "cool-microfinance-bank-limited-ng",
    code: "51458",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 895,
    name: "Cooperative Mortgage Bank",
    slug: "cooperative-mortgage-bank-ng",
    code: "90089",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 283,
    name: "Corestep MFB",
    slug: "corestep-mfb",
    code: "50204",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 173,
    name: "Coronation Merchant Bank",
    slug: "coronation-merchant-bank-ng",
    code: "559",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 694,
    name: "County Finance Limited",
    slug: "county-finance-limited",
    code: "FC40128",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 829,
    name: "Credit Direct Limited",
    slug: "credit-direct-limited-ng",
    code: "40119",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 366,
    name: "Crescent MFB",
    slug: "crescent-mfb",
    code: "51297",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 634,
    name: "Crust Microfinance Bank",
    slug: "crust-microfinance-bank-ng",
    code: "090560",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 820,
    name: "CRUTECH MICROFINANCE BANK LTD",
    slug: "crutech-microfinance-bank-ltd-ng",
    code: "50216",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 865,
    name: "Dash Microfinance Bank",
    slug: "dash-microfinance-bank-ng",
    code: "51368",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 738,
    name: "Davenport MICROFINANCE BANK",
    slug: "davenport-microfinance-bank-ng",
    code: "51334",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 860,
    name: "Dillon Microfinance Bank",
    slug: "dillon-microfinance-bank-ng",
    code: "51450",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 637,
    name: "Dot Microfinance Bank",
    slug: "dot-microfinance-bank-ng",
    code: "50162",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 821,
    name: "EBSU Microfinance Bank",
    slug: "ebsu-microfinance-bank-ng",
    code: "50922",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 4,
    name: "Ecobank Nigeria",
    slug: "ecobank-nigeria",
    code: "050",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 628,
    name: "Ekimogun MFB",
    slug: "ekimogun-mfb-ng",
    code: "50263",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 64,
    name: "Ekondo Microfinance Bank",
    slug: "ekondo-microfinance-bank-ng",
    code: "098",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 914,
    name: "Ethica MFB",
    slug: "ethica-mfb-ng",
    code: "51475",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 761,
    name: "EXCEL FINANCE BANK",
    slug: "excel-finance-bank-ng",
    code: "090678",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 167,
    name: "Eyowo",
    slug: "eyowo",
    code: "50126",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 677,
    name: "Fairmoney Microfinance Bank",
    slug: "fairmoney-microfinance-bank-ng",
    code: "51318",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 898,
    name: "FCMB MFB",
    slug: "fcmb-mfb-ng",
    code: "51241",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 767,
    name: "Fedeth MFB",
    slug: "fedeth-mfb-ng",
    code: "50298",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 916,
    name: "Fewchore Finance Company Limited",
    slug: "fewchore-finance-company-limited-ng",
    code: "050002",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 902,
    name: "FFS Microfinance Bank",
    slug: "ffs-microfinance-bank-ng",
    code: "51110",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 6,
    name: "Fidelity Bank",
    slug: "fidelity-bank",
    code: "070",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 177,
    name: "Firmus MFB",
    slug: "firmus-mfb",
    code: "51314",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 7,
    name: "First Bank of Nigeria",
    slug: "first-bank-of-nigeria",
    code: "011",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 8,
    name: "First City Monument Bank",
    slug: "first-city-monument-bank",
    code: "214",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 893,
    name: "First Option MFB",
    slug: "first-option-mfb-ng",
    code: "50934",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 757,
    name: "FIRST ROYAL MICROFINANCE BANK",
    slug: "first-royal-microfinance-bank-ng",
    code: "090164",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 812,
    name: "FIRSTMIDAS MFB",
    slug: "firstmidas-mfb-ng",
    code: "51333",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 682,
    name: "FirstTrust Mortgage Bank Nigeria",
    slug: "firsttrust-mortgage-bank-nigeria-ng",
    code: "413",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 913,
    name: "Flutterwave MFB",
    slug: "flutterwave-mfb-ng",
    code: "090567",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 882,
    name: "Fortress MFB",
    slug: "fortress-mfb-ng",
    code: "D53",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 112,
    name: "FSDH Merchant Bank Limited",
    slug: "fsdh-merchant-bank-limited",
    code: "501",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 716,
    name: "FUTMINNA MICROFINANCE BANK",
    slug: "futminna-microfinance-bank-ng",
    code: "832",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 794,
    name: "Garun Mallam MFB",
    slug: "garun-mallam-mfb-ng",
    code: "MFB51093",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 287,
    name: "Gateway Mortgage Bank LTD",
    slug: "gateway-mortgage-bank",
    code: "812",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 70,
    name: "Globus Bank",
    slug: "globus-bank",
    code: "00103",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 769,
    name: "Goldman MFB",
    slug: "goldman-mfb-ng",
    code: "090574",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 183,
    name: "GoMoney",
    slug: "gomoney",
    code: "100022",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 756,
    name: "GOOD SHEPHERD MICROFINANCE BANK",
    slug: "good-shepherd-microfinance-bank-ng",
    code: "090664",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 635,
    name: "Goodnews Microfinance Bank",
    slug: "goodnews-microfinance-bank-ng",
    code: "50739",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 633,
    name: "Greenwich Merchant Bank",
    slug: "greenwich-merchant-bank-ng",
    code: "562",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 789,
    name: "GROOMING MICROFINANCE BANK",
    slug: "grooming-microfinance-bank-ng",
    code: "51276",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 824,
    name: "GTI MFB",
    slug: "gti-mfb-ng",
    code: "50368",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 9,
    name: "Guaranty Trust Bank",
    slug: "guaranty-trust-bank",
    code: "058",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 111,
    name: "Hackman Microfinance Bank",
    slug: "hackman-microfinance-bank",
    code: "51251",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 81,
    name: "Hasal Microfinance Bank",
    slug: "hasal-microfinance-bank",
    code: "50383",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 877,
    name: "Hayat Trust MFB",
    slug: "hayat-trust-mfb-ng",
    code: "51364",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 301,
    name: "HopePSB",
    slug: "hopepsb-ng",
    code: "120002",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 75,
    name: "IBANK Microfinance Bank",
    slug: "IBANK-mfb",
    code: "51211",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 828,
    name: "IBBU MFB",
    slug: "ibbu-mfb-ng",
    code: "51279",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 168,
    name: "Ibile Microfinance Bank",
    slug: "ibile-mfb",
    code: "51244",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 859,
    name: "Ibom Mortgage Bank",
    slug: "ibom-mortgage-bank-ng",
    code: "90012",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 615,
    name: "Ikoyi Osun MFB",
    slug: "ikoyi-osun-mfb",
    code: "50439",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 636,
    name: "Ilaro Poly Microfinance Bank",
    slug: "ilaro-poly-microfinance-bank-ng",
    code: "50442",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 703,
    name: "Imowo MFB",
    slug: "imowo-mfb-ng",
    code: "50453",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 754,
    name: "IMPERIAL HOMES MORTAGE BANK",
    slug: "imperial-homes-mortage-bank-ng",
    code: "415",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 858,
    name: "INDULGE MFB",
    slug: "indulge-mfb-ng",
    code: "51392",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 892,
    name: "INEBA GOGO MFB",
    slug: "ineba-gogo-mfb-ng",
    code: "51462",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 172,
    name: "Infinity MFB",
    slug: "infinity-mfb",
    code: "50457",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 822,
    name: "Infinity trust  Mortgage Bank",
    slug: "infinity-trust-mortgage-bank-ng",
    code: "070016",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 787,
    name: "ISUA MFB",
    slug: "isua-mfb-ng",
    code: "090701",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 22,
    name: "Jaiz Bank",
    slug: "jaiz-bank",
    code: "301",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 903,
    name: "Jubilee Life Mortgage Bank",
    slug: "jubilee-life-mortgage-bank-ng",
    code: "402",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 187,
    name: "Kadpoly MFB",
    slug: "kadpoly-mfb",
    code: "50502",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 768,
    name: "KANOPOLY MFB",
    slug: "kanopoly-mfb-ng",
    code: "51308",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 878,
    name: "Kayvee Microfinance Bank",
    slug: "kayvee-microfinance-bank-ng",
    code: "5129",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 894,
    name: "Kebbi Homes Savings and Loans Limited",
    slug: "kebbi-homes-savings-and-loans-limited-ng",
    code: "90028",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 11,
    name: "Keystone Bank",
    slug: "keystone-bank",
    code: "082",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 810,
    name: "Kolomoni MFB",
    slug: "kolomoni-mfb-ng",
    code: "899",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 784,
    name: "KONGAPAY (Kongapay Technologies Limited)(formerly Zinternet)",
    slug: "kongapay-tech-ltd",
    code: "100025",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 184,
    name: "Kredi Money MFB LTD",
    slug: "kredi-money-mfb",
    code: "50200",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 67,
    name: "Kuda Bank",
    slug: "kuda-bank",
    code: "50211",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 109,
    name: "Lagos Building Investment Company Plc.",
    slug: "lbic-plc",
    code: "90052",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 905,
    name: "Lemmy MFB",
    slug: "lemmy-mfb-ng",
    code: "091003",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 523,
    name: "Letshego Microfinance Bank",
    slug: "letshego-microfinance-bank",
    code: "090420",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 180,
    name: "Links MFB",
    slug: "links-mfb",
    code: "50549",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 296,
    name: "Living Trust Mortgage Bank",
    slug: "living-trust-mortgage-bank",
    code: "031",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 753,
    name: "LOMA MFB",
    slug: "loma-mfb-ng",
    code: "50491",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 233,
    name: "Lotus Bank",
    slug: "lotus-bank",
    code: "303",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 873,
    name: "Maal MFB",
    slug: "maal-mfb-ng",
    code: "51444",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 764,
    name: "MAINSTREET MICROFINANCE BANK",
    slug: "mainstreet-microfinance-bank-ng",
    code: "090171",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 175,
    name: "Mayfair MFB",
    slug: "mayfair-mfb",
    code: "50563",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 896,
    name: "Mayfresh Mortgage Bank",
    slug: "mayfresh-mortgage-bank-ng",
    code: "90003",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 887,
    name: "Mega Microfinance Bank",
    slug: "mega-microfinance-bank-ng",
    code: "50570",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 910,
    name: "Michael Okpara UniAgric Microfinance Bank",
    slug: "michael-okpara-uniagric-microfinance-bank-ng",
    code: "MFB51116M",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 178,
    name: "Mint MFB",
    slug: "mint-mfb",
    code: "50304",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 875,
    name: "MINT-FINEX MFB",
    slug: "mint-finex-mfb-ng",
    code: "09",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 714,
    name: "Money Master PSB",
    slug: "money-master-psb-ng",
    code: "946",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 688,
    name: "Moniepoint MFB",
    slug: "moniepoint-mfb-ng",
    code: "50515",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 303,
    name: "MTN Momo PSB",
    slug: "mtn-momo-psb-ng",
    code: "120003",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 739,
    name: "MUTUAL BENEFITS MICROFINANCE BANK",
    slug: "mutual-benefits-microfinance-bank-ng",
    code: "090190",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 758,
    name: "NDCC MICROFINANCE BANK",
    slug: "ndcc-microfinance-bank-ng",
    code: "090679",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 776,
    name: "NET MICROFINANCE BANK",
    slug: "net-microfinance-bank-ng",
    code: "51361",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 774,
    name: "Nigerian Navy Microfinance Bank Limited",
    slug: "nigerian-navy-microfinance-bank-limited-ng",
    code: "51142",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 883,
    name: "NIRSAL MICROFINANCE",
    slug: "nirsal-microfinance-ng",
    code: "51304",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 795,
    name: "Nombank MFB",
    slug: "nombank-mfb-ng",
    code: "50072",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 801,
    name: "NOVA BANK",
    slug: "nova-bank-ng",
    code: "561",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 830,
    name: "Novus MFB",
    slug: "novus-mfb-ng",
    code: "51371",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 715,
    name: "NPF MICROFINANCE BANK",
    slug: "npf-microfinance-bank-ng",
    code: "50629",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 825,
    name: "NSUK MICROFINANACE BANK",
    slug: "nsuk-microfinanace-bank-ng",
    code: "51261",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 863,
    name: "Olabisi Onabanjo University Microfinance Bank",
    slug: "olabisi-onabanjo-university-microfinance-bank-ng",
    code: "50689",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 802,
    name: "OLUCHUKWU MICROFINANCE BANK LTD",
    slug: "oluchukwu-microfinance-bank-ltd-ng",
    code: "50697",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 171,
    name: "OPay Digital Services Limited (OPay)",
    slug: "paycom",
    code: "999992",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 699,
    name: "Optimus Bank Limited",
    slug: "optimus-bank-ltd",
    code: "107",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 912,
    name: "Pact Microfinance Bank",
    slug: "pact-microfinance-bank-ng",
    code: "51477",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 185,
    name: "Paga",
    slug: "paga",
    code: "100002",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 169,
    name: "PalmPay",
    slug: "palmpay",
    code: "999991",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 26,
    name: "Parallex Bank",
    slug: "parallex-bank",
    code: "104",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 110,
    name: "Parkway - ReadyCash",
    slug: "parkway-ready-cash",
    code: "311",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 763,
    name: "PATHFINDER MICROFINANCE BANK LIMITED",
    slug: "pathfinder-microfinance-bank-limited-ng",
    code: "090680",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 884,
    name: "Paystack MFB",
    slug: "paystack-mfb-ng",
    code: "51457",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 629,
    name: "Paystack-Titan",
    slug: "titan-paystack",
    code: "100039",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 693,
    name: "Peace Microfinance Bank",
    slug: "peace-microfinance-bank-ng",
    code: "50743",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 775,
    name: "PECANTRUST MICROFINANCE BANK LIMITED",
    slug: "pecantrust-microfinance-bank-limited-ng",
    code: "51226",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 683,
    name: "Personal Trust MFB",
    slug: "personal-trust-mfb-ng",
    code: "51146",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 170,
    name: "Petra Mircofinance Bank Plc",
    slug: "petra-microfinance-bank-plc",
    code: "50746",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 831,
    name: "Pettysave MFB",
    slug: "pettysave-mfb-ng",
    code: "MFB51452",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 762,
    name: "PFI FINANCE COMPANY LIMITED",
    slug: "pfi-finance-company-limited-ng",
    code: "050021",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 705,
    name: "Platinum Mortgage Bank",
    slug: "platinum-mortgage-bank-ng",
    code: "268",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 770,
    name: "Pocket App",
    slug: "pocket",
    code: "00716",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 13,
    name: "Polaris Bank",
    slug: "polaris-bank",
    code: "076",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 626,
    name: "Polyunwana MFB",
    slug: "polyunwana-mfb-ng",
    code: "50864",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 304,
    name: "PremiumTrust Bank",
    slug: "premiumtrust-bank-ng",
    code: "105",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 792,
    name: "Prospa Capital Microfinance Bank",
    slug: "prospa-capital-microfinance-bank-ng",
    code: "50739",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 760,
    name: "PROSPERIS FINANCE LIMITED",
    slug: "prosperis-finance-limited-ng",
    code: "050023",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 25,
    name: "Providus Bank",
    slug: "providus-bank",
    code: "101",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 232,
    name: "QuickFund MFB",
    slug: "quickfund-mfb",
    code: "51293",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 176,
    name: "Rand Merchant Bank",
    slug: "rand-merchant-bank",
    code: "502",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 766,
    name: "RANDALPHA MICROFINANCE BANK",
    slug: "randalpha-microfinance-bank-ng",
    code: "090496",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 918,
    name: "Rank MFB",
    slug: "rank-mfb-ng",
    code: "50130",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 295,
    name: "Refuge Mortgage Bank",
    slug: "refuge-mortgage-bank",
    code: "90067",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 773,
    name: "REHOBOTH MICROFINANCE BANK",
    slug: "rehoboth-microfinance-bank-ng",
    code: "50761",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 710,
    name: "Rephidim Microfinance Bank",
    slug: "rephidim",
    code: "50994",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 885,
    name: "Retrust Mfb",
    slug: "retrust-mfb-ng",
    code: "51375",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 907,
    name: "Rex Microfinance Bank",
    slug: "rex-microfinance-bank-ng",
    code: "51108",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 700,
    name: "Rigo Microfinance Bank Limited",
    slug: "rigo-microfinance-bank-limited-ng",
    code: "51286",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 679,
    name: "ROCKSHIELD MICROFINANCE BANK",
    slug: "rockshield-microfinance-bank-ng",
    code: "50767",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 69,
    name: "Rubies MFB",
    slug: "rubies-mfb",
    code: "125",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 286,
    name: "Safe Haven MFB",
    slug: "safe-haven-mfb-ng",
    code: "51113",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 706,
    name: "SAGE GREY FINANCE LIMITED",
    slug: "sage-grey-finance-limited-ng",
    code: "40165",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 632,
    name: "Shield MFB",
    slug: "shield-mfb-ng",
    code: "50582",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 750,
    name: "Signature Bank Ltd",
    slug: "signature-bank-ltd-ng",
    code: "106",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 695,
    name: "Solid Allianze MFB",
    slug: "solid-allianze-mfb",
    code: "51062",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 365,
    name: "Solid Rock MFB",
    slug: "solid-rock-mfb",
    code: "50800",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 72,
    name: "Sparkle Microfinance Bank",
    slug: "sparkle-microfinance-bank",
    code: "51310",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 855,
    name: "Springfield Microfinance Bank",
    slug: "springfield-microfinance-bank-ng",
    code: "51429",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 14,
    name: "Stanbic IBTC Bank",
    slug: "stanbic-ibtc-bank",
    code: "221",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 15,
    name: "Standard Chartered Bank",
    slug: "standard-chartered-bank",
    code: "068",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 765,
    name: "STANFORD MICROFINANCE BANK",
    slug: "stanford-microfinance-bank-ng",
    code: "090162",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 779,
    name: "STATESIDE MICROFINANCE BANK",
    slug: "stateside-microfinance-bank-ng",
    code: "50809",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 826,
    name: "STB Mortgage Bank",
    slug: "stb-mortgage-bank-ng",
    code: "070022",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 285,
    name: "Stellas MFB",
    slug: "stellas-mfb",
    code: "51253",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 16,
    name: "Sterling Bank",
    slug: "sterling-bank",
    code: "232",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 869,
    name: "Summit Bank",
    slug: "summit-bank-ng",
    code: "00305",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 23,
    name: "Suntrust Bank",
    slug: "suntrust-bank",
    code: "100",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 631,
    name: "Supreme MFB",
    slug: "supreme-mfb-ng",
    code: "50968",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 888,
    name: "Sycamore Microfinance Bank",
    slug: "sycamore-microfinance-bank-ng",
    code: "51056",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 68,
    name: "TAJ Bank",
    slug: "taj-bank",
    code: "302",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 186,
    name: "Tangerine Money",
    slug: "tangerine-money",
    code: "51269",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 889,
    name: "Tatum Bank",
    slug: "tatum-bank-ng",
    code: "109",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 811,
    name: "TENN",
    slug: "tenn-ng",
    code: "51403",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 866,
    name: "Think Finance Microfinance Bank",
    slug: "think-finance-microfinance-bank-ng",
    code: "677",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 73,
    name: "Titan Bank",
    slug: "titan-bank",
    code: "102",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 788,
    name: "TransPay MFB",
    slug: "transpay-mfb-ng",
    code: "090708",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 862,
    name: "TRUSTBANC J6 MICROFINANCE BANK",
    slug: "trustbanc-j6-microfinance-bank-ng",
    code: "51118",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 919,
    name: "U and C MFB",
    slug: "u-and-c-mfb-ng",
    code: "50840",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 690,
    name: "U&C Microfinance Bank Ltd (U AND C MFB)",
    slug: "uc-microfinance-bank-ltd-u-and-c-mfb-ng",
    code: "50840",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 786,
    name: "UCEE MFB",
    slug: "ucee-mfb-ng",
    code: "090706",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 630,
    name: "Uhuru MFB",
    slug: "uhuru-mfb-ng",
    code: "51322",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 853,
    name: "Ultraviolet Microfinance Bank",
    slug: "ultraviolet-microfinance-bank-ng",
    code: "51080",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 678,
    name: "Unaab Microfinance Bank Limited",
    slug: "unaab-microfinance-bank-limited-ng",
    code: "50870",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 861,
    name: "UNIABUJA MFB",
    slug: "uniabuja-mfb",
    code: "51447",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 282,
    name: "Unical MFB",
    slug: "unical-mfb",
    code: "50871",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 638,
    name: "Unilag Microfinance Bank",
    slug: "unilag-microfinance-bank-ng",
    code: "51316",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 823,
    name: "UNIMAID MICROFINANCE BANK",
    slug: "unimaid-microfinance-bank-ng",
    code: "50875",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 17,
    name: "Union Bank of Nigeria",
    slug: "union-bank-of-nigeria",
    code: "032",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 18,
    name: "United Bank For Africa",
    slug: "united-bank-for-africa",
    code: "033",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 19,
    name: "Unity Bank",
    slug: "unity-bank",
    code: "215",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 881,
    name: "UNIUYO Microfinance Bank Ltd",
    slug: "uniuyo-microfinance-bank-ltd-ng",
    code: "50880",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 737,
    name: "Uzondu Microfinance Bank Awka Anambra State",
    slug: "uzondu-microfinance-bank-awka-anambra-state-ng",
    code: "50894",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 725,
    name: "Vale Finance Limited",
    slug: "vale-finance",
    code: "050020",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 71,
    name: "VFD Microfinance Bank Limited",
    slug: "vfd",
    code: "566",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 909,
    name: "Victory MFB",
    slug: "victory-mfb-ng",
    code: "51085",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 701,
    name: "Waya Microfinance Bank",
    slug: "waya-microfinance-bank-ng",
    code: "51355",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 20,
    name: "Wema Bank",
    slug: "wema-bank",
    code: "035",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 854,
    name: "Weston Charis MFB",
    slug: "weston-charis-mfb-ng",
    code: "51386",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 917,
    name: "Whitecrust Finance Company",
    slug: "whitecrust-finance-company-ng",
    code: "402001",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 827,
    name: "Xpress Wallet",
    slug: "xpress-wallet-ng",
    code: "100040",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 911,
    name: "YCT MFB",
    slug: "yct-mfb-ng",
    code: "51253",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 797,
    name: "Yes MFB",
    slug: "yes-mfb-ng",
    code: "594",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 870,
    name: "Zap",
    slug: "zap",
    code: "00zap",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 21,
    name: "Zenith Bank",
    slug: "zenith-bank",
    code: "057",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    id: 65,
    name: "Zenith Bank",
    slug: "zenith-bank-usd",
    code: "057",
    country: "Nigeria",
    currency: "USD",
    type: "nuban",
  },
  {
    id: 876,
    name: "Zitra MFB",
    slug: "zitra-mfb-ng",
    code: "51373",
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
];
