import { describe, expect, it, vi } from "vitest";
import { createWarpDemoService } from "./warp-demo.service.js";
import { createWarpDemoSessionStore } from "./warp-demo-session.store.js";
import { createWarpDemoSandboxEngine } from "./warp-demo-sandbox.engine.js";
import { MemoryWarpDemoRedis } from "./warp-demo-test-redis.js";
import type { PolicyReconciliationJob } from "../../queues/policy-reconciliation.types.js";

const businessId = "68b000000000000000000001"; const mayaId = "68b000000000000000000000011"; const engineering = "68b000000000000000000000005"; const finance = "68b000000000000000000000009"; const fullTime = "68b000000000000000000000006"; const contractor = "68b000000000000000000000010"; const remote = "68b000000000000000000000012"; const categoryId = "68b000000000000000000000004"; const githubPolicy = "68b000000000000000000000003"; const financePolicy = "68b000000000000000000000013"; const engineeringRule = "68b000000000000000000000008"; const financeRule = "68b000000000000000000000014";

const setup = () => {
  const mongoEmployee = { _id: mayaId, fullName: "Maya Patel", jobTitle: "Software Engineer", employeeListId: engineering, employeeTypeId: fullTime, groupIds: [remote], state: "California", status: "active", employmentStartDate: new Date("2024-01-01") };
  const repository = {
    findBusiness: vi.fn(async () => ({ _id: businessId, name: "Northstar Labs", email: "warp-demo@northstar.invalid" })), listEmployees: vi.fn(async () => [mongoEmployee]), findEmployee: vi.fn(async () => mongoEmployee), findEmployeeByName: vi.fn(async () => mongoEmployee),
    listEmployeeLists: vi.fn(async () => [{ _id: engineering, name: "Engineering", status: "active" }, { _id: finance, name: "Finance", status: "active" }]), listEmployeeTypes: vi.fn(async () => [{ _id: fullTime, name: "Full Time", status: "active" }, { _id: contractor, name: "Contractor", status: "active" }]), listEmployeeGroups: vi.fn(async () => [{ _id: remote, name: "Remote", status: "active" }]),
    listCategories: vi.fn(async () => [{ _id: categoryId, name: "Application Access", cardinality: "MANY", status: "active" }]), listPolicies: vi.fn(async () => [{ _id: githubPolicy, categoryId, name: "GitHub Access", version: 1, status: "active", effectiveFrom: null, effectiveTo: null, configuration: { demo: true } }, { _id: financePolicy, categoryId, name: "Finance Access", version: 1, status: "active", effectiveFrom: null, effectiveTo: null, configuration: { demo: true } }]), findPolicy: vi.fn(async () => null),
    listRules: vi.fn(async () => [{ _id: engineeringRule, policyId: githubPolicy, name: "Engineering", conditions: [{ field: "department", operator: "equals", value: engineering }], priority: 20, version: 1, status: "active", effectiveFrom: null, effectiveTo: null }, { _id: financeRule, policyId: financePolicy, name: "Finance", conditions: [{ field: "department", operator: "equals", value: finance }], priority: 20, version: 1, status: "active", effectiveFrom: null, effectiveTo: null }]),
    listActiveAssignments: vi.fn(async () => []), countActiveRules: vi.fn(async () => 2), countActiveAssignments: vi.fn(async () => 0), listAudit: vi.fn(async () => []), findGitHubConnection: vi.fn(async () => ({ status: "active", installationId: 99 })), countManagedExternalGrants: vi.fn(async () => 4),
  };
  const redis = new MemoryWarpDemoRedis(); const store = createWarpDemoSessionStore({ redis, sessionTtlSeconds: 900, maxMutations: 12 }); const createHttpError = (message: string, statusCode: number) => Object.assign(new Error(message), { statusCode }); const engine = createWarpDemoSandboxEngine({ store, createHttpError }); const jobs: PolicyReconciliationJob[] = [];
  const progress = { createRun: vi.fn(async () => undefined), appendEvent: vi.fn(async () => undefined), markFailed: vi.fn(async () => undefined), getRun: vi.fn(async () => null) };
  const resolver = { resolvePoliciesForEmployee: vi.fn() };
  const service = createWarpDemoService({ repository: repository as any, resolver: resolver as any, businessId, createHttpError, sessionStore: store, sandboxEngine: engine, progressService: progress as any, enqueueReconciliation: async (job) => { jobs.push(job); return { id: "queued" }; } });
  const process = async (job = jobs.at(-1)!) => { if (job.type !== "RECONCILE_WARP_DEMO") throw new Error("Expected demo job"); return engine.reconcile({ sessionId: job.sessionId, runId: job.runId, revision: job.revision, reason: job.reason, employeeChanged: job.employeeChanged, asOfDate: new Date() }); };
  return { service, store, engine, jobs, process, repository, mongoEmployee };
};

describe("Warp demo Redis sandboxes", () => {
  it("creates concurrent independent sessions from the canonical seed", async () => { const fixture = setup(); const [a, b] = await Promise.all([fixture.service.createSession(), fixture.service.createSession()]); expect(a.sessionId).not.toBe(b.sessionId); expect(a.employee).toMatchObject({ alias: "maya", department: "Engineering" }); expect(b.employee).toMatchObject({ department: "Engineering" }); });
  it("changes only session A and leaves session B and Mongo unchanged", async () => { const fixture = setup(); const a = await fixture.service.createSession(); await fixture.process(fixture.jobs[0]); const b = await fixture.service.createSession(); await fixture.process(fixture.jobs[1]); await fixture.service.mutate(a.sessionId, { employee: "maya", field: "department", value: "finance" }); await fixture.process(); expect(await fixture.service.sessionEmployee(a.sessionId)).toMatchObject({ department: "Finance" }); expect(await fixture.service.sessionEmployee(b.sessionId)).toMatchObject({ department: "Engineering" }); expect(fixture.mongoEmployee.employeeListId).toBe(engineering); });
  it("uses real policy resolution and records session assignment transitions and audit", async () => { const fixture = setup(); const session = await fixture.service.createSession(); await fixture.process(); expect((await fixture.service.sessionEmployeePolicies(session.sessionId)).policies.map((item) => item.name)).toEqual(["GitHub Access"]); await fixture.service.mutate(session.sessionId, { employee: "maya", field: "department", value: "finance" }); await fixture.process(); expect((await fixture.service.sessionEmployeePolicies(session.sessionId)).policies.map((item) => item.name)).toEqual(["Finance Access"]); const audit = await fixture.service.sessionAudit(session.sessionId); expect(audit.events.map((item) => item.action)).toEqual(expect.arrayContaining(["EMPLOYEE_UPDATED", "ASSIGNMENT_ENDED", "ASSIGNMENT_CREATED"])); });
  it("uses copied reference data for expected and actual sandbox explanation labels", async () => { const fixture = setup(); const session = await fixture.service.createSession(); await fixture.process(); const explanation = await fixture.service.sessionExplain(session.sessionId); const financeRuleEvaluation = explanation.evaluatedRules.find((item: any) => item.ruleId === financeRule); expect(financeRuleEvaluation).toMatchObject({ ruleName: "Finance", matched: false, conditions: [expect.objectContaining({ condition: expect.objectContaining({ value: finance }), actualValue: engineering, expectedDisplayValue: "Finance", actualDisplayValue: "Engineering", matched: false })] }); expect(explanation.categories.flatMap((item: any) => item.selectedPolicies).map((item: any) => item.name)).toEqual(["GitHub Access"]); });
  it("preserves IDs and dates through Redis serialization", async () => { const fixture = setup(); const session = await fixture.service.createSession(); await fixture.process(); const stored = await fixture.store.getSession(session.sessionId); expect(stored.employee.id).toBe(mayaId); expect(stored.employee.employmentStartDate).toBe("2024-01-01T00:00:00.000Z"); expect(stored.assignments[0]?.effectiveFrom).toMatch(/^\d{4}-\d{2}-\d{2}T/); });
  it("resets only its sandbox and supersedes old revisions", async () => { const fixture = setup(); const session = await fixture.service.createSession(); await fixture.process(); await fixture.service.mutate(session.sessionId, { employee: "maya", field: "state", value: "new_york" }); const stale = fixture.jobs.at(-1)!; const reset = await fixture.service.reset(session.sessionId); await fixture.process(); if (stale.type !== "RECONCILE_WARP_DEMO") throw new Error("Expected demo job"); expect((await fixture.engine.reconcile({ sessionId: stale.sessionId, runId: stale.runId, revision: stale.revision, reason: stale.reason, employeeChanged: true })).stale).toBe(true); expect(await fixture.service.sessionEmployee(session.sessionId)).toMatchObject({ state: "California" }); expect(reset.status).toBe("queued"); });
  it("never calls production employee writes, grants, or GitHub despite seeded connection records", async () => { const fixture = setup(); const session = await fixture.service.createSession(); await fixture.process(); expect(session.sessionId).toBeTruthy(); expect(fixture.repository.findGitHubConnection).not.toHaveBeenCalled(); expect(fixture.repository.countManagedExternalGrants).not.toHaveBeenCalled(); });
  it("assigns each queued job to exactly one session", async () => { const fixture = setup(); const a = await fixture.service.createSession(); const b = await fixture.service.createSession(); const first = fixture.jobs[0]; const second = fixture.jobs[1]; if (first.type !== "RECONCILE_WARP_DEMO" || second.type !== "RECONCILE_WARP_DEMO") throw new Error("Expected demo jobs"); expect(first.sessionId).toBe(a.sessionId); expect(second.sessionId).toBe(b.sessionId); expect(first.sessionId).not.toBe(second.sessionId); });
});
