import { asyncHandler } from "../../utils/async-handler.js";
import type { Request, Response } from "express";
import { enqueuePolicyReconciliation } from "../../queues/policy-reconciliation.queue.js";
import type { PolicyService } from "./policy.service.js";
import type { PolicyResolver } from "./policy-resolver.service.js";
import type { PolicyReconciliationService } from "./policy-reconciliation.service.js";
import type { PolicyAuditService } from "../policy-audit/policy-audit.service.js";
import * as schemas from "./policy.validators.js";

type Dependencies = { policyService: PolicyService; resolver: PolicyResolver; reconciliationService: PolicyReconciliationService; auditService: PolicyAuditService };
const userId = (req: Request) => req.user!.id;
const ok = (res: Response, data: unknown, message: string, status = 200) => res.status(status).json({ success: true, message, data });

export const createPolicyController = ({ policyService, resolver, reconciliationService, auditService }: Dependencies) => ({
  listCategories: asyncHandler(async (req, res) => { const { businessId } = schemas.listCategoriesSchema.shape.params.parse(req.validatedParams); const { page, limit, status } = schemas.listCategoriesSchema.shape.query.parse(req.validatedQuery); return ok(res, await policyService.listCategories(businessId, page, limit, status), "Policy categories retrieved"); }),
  getCategory: asyncHandler(async (req, res) => { const { businessId, categoryId } = schemas.categoryParamsSchema.shape.params.parse(req.validatedParams); return ok(res, (await policyService.getCategory(businessId, categoryId)).category, "Policy category retrieved"); }),
  createCategory: asyncHandler(async (req, res) => { const { businessId } = schemas.createCategorySchema.shape.params.parse(req.validatedParams); const body = schemas.createCategorySchema.shape.body.parse(req.validatedBody); return ok(res, (await policyService.createCategory(businessId, userId(req), body)).category, "Policy category created", 201); }),
  updateCategory: asyncHandler(async (req, res) => { const { businessId, categoryId } = schemas.updateCategorySchema.shape.params.parse(req.validatedParams); const body = schemas.updateCategorySchema.shape.body.parse(req.validatedBody); return ok(res, (await policyService.updateCategory(businessId, categoryId, userId(req), body)).category, "Policy category updated"); }),
  archiveCategory: asyncHandler(async (req, res) => { const { businessId, categoryId } = schemas.categoryParamsSchema.shape.params.parse(req.validatedParams); return ok(res, (await policyService.updateCategory(businessId, categoryId, userId(req), { status: "archived" })).category, "Policy category archived"); }),

  listPolicies: asyncHandler(async (req, res) => { const { businessId } = schemas.listPoliciesSchema.shape.params.parse(req.validatedParams); const { page, limit, categoryId, status } = schemas.listPoliciesSchema.shape.query.parse(req.validatedQuery); return ok(res, await policyService.listPolicies(businessId, page, limit, categoryId, status), "Policies retrieved"); }),
  getPolicy: asyncHandler(async (req, res) => { const { businessId, policyId } = schemas.policyParamsSchema.shape.params.parse(req.validatedParams); return ok(res, (await policyService.getPolicy(businessId, policyId)).policy, "Policy retrieved"); }),
  createPolicy: asyncHandler(async (req, res) => { const { businessId } = schemas.createPolicySchema.shape.params.parse(req.validatedParams); const body = schemas.createPolicySchema.shape.body.parse(req.validatedBody); return ok(res, (await policyService.createPolicy(businessId, userId(req), body)).policy, "Policy created", 201); }),
  updatePolicy: asyncHandler(async (req, res) => { const { businessId, policyId } = schemas.updatePolicySchema.shape.params.parse(req.validatedParams); const body = schemas.updatePolicySchema.shape.body.parse(req.validatedBody); return ok(res, (await policyService.updatePolicy(businessId, policyId, userId(req), body)).policy, "Policy updated"); }),
  activatePolicy: asyncHandler(async (req, res) => { const { businessId, policyId } = schemas.policyParamsSchema.shape.params.parse(req.validatedParams); return ok(res, (await policyService.updatePolicy(businessId, policyId, userId(req), { status: "active" }, "POLICY_ACTIVATED")).policy, "Policy activated"); }),
  archivePolicy: asyncHandler(async (req, res) => { const { businessId, policyId } = schemas.policyParamsSchema.shape.params.parse(req.validatedParams); return ok(res, (await policyService.updatePolicy(businessId, policyId, userId(req), { status: "archived" }, "POLICY_ARCHIVED")).policy, "Policy archived"); }),

  listRules: asyncHandler(async (req, res) => { const { businessId, policyId } = schemas.listRulesSchema.shape.params.parse(req.validatedParams); return ok(res, await policyService.listRules(businessId, policyId), "Policy rules retrieved"); }),
  getRule: asyncHandler(async (req, res) => { const { businessId, ruleId } = schemas.ruleParamsSchema.shape.params.parse(req.validatedParams); return ok(res, (await policyService.getRule(businessId, ruleId)).rule, "Policy rule retrieved"); }),
  createRule: asyncHandler(async (req, res) => { const { businessId, policyId } = schemas.createRuleSchema.shape.params.parse(req.validatedParams); const body = schemas.createRuleSchema.shape.body.parse(req.validatedBody); return ok(res, (await policyService.createRule(businessId, policyId, userId(req), body)).rule, "Policy rule created", 201); }),
  updateRule: asyncHandler(async (req, res) => { const { businessId, ruleId } = schemas.updateRuleSchema.shape.params.parse(req.validatedParams); const body = schemas.updateRuleSchema.shape.body.parse(req.validatedBody); return ok(res, (await policyService.updateRule(businessId, ruleId, userId(req), body)).rule, "Policy rule updated"); }),
  enableRule: asyncHandler(async (req, res) => { const { businessId, ruleId } = schemas.ruleParamsSchema.shape.params.parse(req.validatedParams); return ok(res, (await policyService.updateRule(businessId, ruleId, userId(req), { status: "active" }, "RULE_ENABLED")).rule, "Policy rule enabled"); }),
  disableRule: asyncHandler(async (req, res) => { const { businessId, ruleId } = schemas.ruleParamsSchema.shape.params.parse(req.validatedParams); return ok(res, (await policyService.updateRule(businessId, ruleId, userId(req), { status: "disabled" }, "RULE_DISABLED")).rule, "Policy rule disabled"); }),

  employeePolicies: asyncHandler(async (req, res) => { const params = schemas.employeePoliciesSchema.shape.params.parse(req.validatedParams); const { asOf } = schemas.employeePoliciesSchema.shape.query.parse(req.validatedQuery); return ok(res, { items: await reconciliationService.getAssignments(params.businessId, params.employeeId, asOf), asOf, intervalSemantics: "effectiveFrom <= asOf < effectiveTo" }, "Employee policies retrieved"); }),
  explainEmployeePolicies: asyncHandler(async (req, res) => { const params = schemas.employeePoliciesSchema.shape.params.parse(req.validatedParams); const { asOf } = schemas.employeePoliciesSchema.shape.query.parse(req.validatedQuery); return ok(res, { ...(await resolver.resolvePoliciesForEmployee({ businessId: params.businessId, employeeId: params.employeeId, asOfDate: asOf })), historicalEmployeeAttributeSnapshotAvailable: false }, "Employee policy explanation generated"); }),
  createManualAssignment: asyncHandler(async (req, res) => { const params = schemas.manualAssignmentSchema.shape.params.parse(req.validatedParams); const { effectiveFrom } = schemas.manualAssignmentSchema.shape.body.parse(req.validatedBody); const actor = await policyService.actor(params.businessId, userId(req)); const result = await reconciliationService.createManualAssignment({ ...params, userId: userId(req), businessMemberId: actor.actorBusinessMemberId, effectiveFrom }); await enqueuePolicyReconciliation({ type: "RECONCILE_EMPLOYEE", businessId: params.businessId, employeeId: params.employeeId, reason: "manual_assignment.created", requestedBy: userId(req), requestedAt: new Date().toISOString(), correlationId: req.id }).catch((error) => console.error("Failed to enqueue manual-assignment reconciliation", { businessId: params.businessId, employeeId: params.employeeId, error })); return ok(res, result.assignment, result.created ? "Manual assignment created" : "Manual assignment already active", result.created ? 201 : 200); }),
  endManualAssignment: asyncHandler(async (req, res) => { const params = schemas.endManualAssignmentSchema.shape.params.parse(req.validatedParams); const { effectiveTo } = schemas.endManualAssignmentSchema.shape.body.parse(req.validatedBody); const actor = await policyService.actor(params.businessId, userId(req)); const result = await reconciliationService.endManualAssignment({ ...params, userId: userId(req), businessMemberId: actor.actorBusinessMemberId, effectiveTo }); await enqueuePolicyReconciliation({ type: "RECONCILE_EMPLOYEE", businessId: params.businessId, employeeId: params.employeeId, reason: "manual_assignment.ended", requestedBy: userId(req), requestedAt: new Date().toISOString(), correlationId: req.id }).catch((error) => console.error("Failed to enqueue manual-assignment reconciliation", { businessId: params.businessId, employeeId: params.employeeId, error })); return ok(res, result.assignment, "Manual assignment ended"); }),
  reconcileEmployee: asyncHandler(async (req, res) => { const params = schemas.reconcileEmployeeSchema.shape.params.parse(req.validatedParams); const { reason } = schemas.reconcileEmployeeSchema.shape.body.parse(req.validatedBody); const job = await enqueuePolicyReconciliation({ type: "RECONCILE_EMPLOYEE", ...params, reason, requestedBy: userId(req), requestedAt: new Date().toISOString(), correlationId: req.id }); if (!job) return res.status(503).json({ success: false, message: "Policy reconciliation queue is unavailable" }); return ok(res, { jobId: job.id }, "Policy reconciliation queued", 202); }),
  reconcileBusiness: asyncHandler(async (req, res) => { const { businessId } = schemas.reconcileBusinessSchema.shape.params.parse(req.validatedParams); const { reason } = schemas.reconcileBusinessSchema.shape.body.parse(req.validatedBody); const job = await enqueuePolicyReconciliation({ type: "RECONCILE_BUSINESS", businessId, reason, requestedBy: userId(req), requestedAt: new Date().toISOString(), correlationId: req.id }); if (!job) return res.status(503).json({ success: false, message: "Policy reconciliation queue is unavailable" }); return ok(res, { jobId: job.id }, "Business policy reconciliation queued", 202); }),
  listAudit: asyncHandler(async (req, res) => { const { businessId } = schemas.listAuditSchema.shape.params.parse(req.validatedParams); const { page, limit, ...filters } = schemas.listAuditSchema.shape.query.parse(req.validatedQuery); return ok(res, await auditService.list({ businessId, filters, page, limit }), "Policy audit retrieved"); }),
  employeeHistory: asyncHandler(async (req, res) => { const { businessId, employeeId } = schemas.employeeHistorySchema.shape.params.parse(req.validatedParams); const { page, limit, ...dates } = schemas.employeeHistorySchema.shape.query.parse(req.validatedQuery); return ok(res, await auditService.list({ businessId, filters: { employeeId, ...dates }, page, limit }), "Employee policy history retrieved"); }),
  policyHistory: asyncHandler(async (req, res) => { const { businessId, policyId } = schemas.policyHistorySchema.shape.params.parse(req.validatedParams); const { page, limit, ...dates } = schemas.policyHistorySchema.shape.query.parse(req.validatedQuery); return ok(res, await auditService.list({ businessId, filters: { policyId, ...dates }, page, limit }), "Policy history retrieved"); }),
  ruleHistory: asyncHandler(async (req, res) => { const { businessId, ruleId } = schemas.ruleHistorySchema.shape.params.parse(req.validatedParams); const { page, limit, ...dates } = schemas.ruleHistorySchema.shape.query.parse(req.validatedQuery); return ok(res, await auditService.list({ businessId, filters: { ruleId, ...dates }, page, limit }), "Policy rule history retrieved"); }),
});
